install:
  - choco install gitversion.portable -version 3.0.0-beta0004 -pre -y

nuget:
  account_feed: true

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

configuration: Release

build:
  project: PlayerRank.sln
  verbosity: minimal

after_build:
  - cmd: nuget pack PlayerRank\PlayerRank.csproj -version "%GitVersion_NuGetVersion%" -prop "target=Release"
  - cmd: appveyor PushArtifact "PlayerRank.%GitVersion_NuGetVersion%.nupkg"