install:
  - choco install gitversion.portable -version 3.0.0-beta0004 -pre -y

nuget:
  account_feed: true

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

configuration: Release

build:
  project: PlayerRank.sln
  verbosity: minimal

after_build:
  - cmd: nuget pack PlayerRank\PlayerRank.csproj -version "%GitVersion_NuGetVersion%" -prop "target=Release"
  - cmd: appveyor PushArtifact "PlayerRank.%GitVersion_NuGetVersion%.nupkg"
  
  deploy:
  - provider: GitHub
    auth_token:
      secure: A7+/5adwhz9NXkJeVJpckt7wIcfIOVr1M8KPMHrOD+TknNaV6CX2XrKR21+QS9ko
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    release: v$(GitVersion_NuGetVersion)
    description: 'Placeholder'
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: mJ21/ayGYSXI/29RaN75qvcuoYDIq8RKmq7PkBlkQ8WWUnfZ063XDmhNrELUKwXP
    skip_symbols: false
    on:
      appveyor_repo_tag: true