configuration: Release
image: Visual Studio 2017 Preview

install:
  - choco install GitVersion.Portable
  - GitVersion /output buildserver

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%GitVersion_MajorMinorPatch%'
  package_version: '%GitVersion_NuGetVersion%'

before_build:
  - dotnet restore

build:
  project: PlayerRank.sln
  verbosity: minimal

after_build:
  - cmd: dotnet pack PlayerRank\PlayerRank.csproj -c Release
  - cmd: appveyor PushArtifact "PlayerRank\bin\release\PlayerRank.%GitVersion_NuGetVersion%.nupkg"

deploy:
  - provider: GitHub
    auth_token:
      secure: A7+/5adwhz9NXkJeVJpckt7wIcfIOVr1M8KPMHrOD+TknNaV6CX2XrKR21+QS9ko
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    description: ''
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: mJ21/ayGYSXI/29RaN75qvcuoYDIq8RKmq7PkBlkQ8WWUnfZ063XDmhNrELUKwXP
    skip_symbols: false
    on:
      appveyor_repo_tag: true