name: Build + Release

on:
  push:
    branches:
      - "main"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:7.0
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: NuGet

      - name: Release - GitHub
        run: ./.build/release-github.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} NuGet ${{ secrets.NUGET_TOKEN }}

      - name: Release - NuGet.org
        run: ./.build/release-nuget.sh ${{ secrets.NUGET_TOKEN }}
